server:
  port: 8082

spring:
  jmx:
    enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Thakur@7

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    sampling:
      probability: 1.0


#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}