server:
  port: 8082

spring:
  jmx:
    enabled: true
  zipkin:
    base-url: http://localhost:9411

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Thakur@7

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9296

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

management:
  tracing:
    sampling:
      probability: 1.0


#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}